import { defineField, defineType } from 'sanity'

// AI-First: AI最適化コンテンツエンティティ
export default defineType({
  name: 'aiContent',
  title: 'AI最適化コンテンツ',
  type: 'document',

  groups: [
    { name: 'ai', title: 'AI最適化' },
    { name: 'basic', title: '基本情報' },
    { name: 'relations', title: '関連情報' }
  ],

  fields: [
    // ========== AI最適化フィールド ==========
    defineField({
      name: 'aiSearchKeywords',
      title: 'AI検索キーワード',
      description: 'AIがこのコンテンツを検索する際のキーワード',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'ai',
      validation: Rule => Rule.required()
    }),

    defineField({
      name: 'aiSummary',
      title: 'AI要約',
      description: 'AIが回答で使用する要約文',
      type: 'text',
      group: 'ai',
      validation: Rule => Rule.required().max(300)
    }),

    defineField({
      name: 'aiContext',
      title: 'AI文脈情報',
      type: 'object',
      group: 'ai',
      fields: [
        {
          name: 'relevantQuestions',
          title: '関連する質問パターン',
          type: 'array',
          of: [{ type: 'string' }]
        },
        {
          name: 'responseHints',
          title: 'AI回答のヒント',
          type: 'text'
        }
      ]
    }),

    defineField({
      name: 'aiPriority',
      title: 'AI検索優先度',
      type: 'number',
      group: 'ai',
      validation: Rule => Rule.min(0).max(10),
      initialValue: 5
    }),

    // ========== 基本情報 ==========
    defineField({
      name: 'title',
      title: 'タイトル',
      type: 'string',
      group: 'basic',
      validation: Rule => Rule.required()
    }),

    defineField({
      name: 'contentType',
      title: 'コンテンツタイプ',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          { title: 'ブログ記事', value: 'blog' },
          { title: 'ページ', value: 'page' },
          { title: 'ニュース', value: 'news' },
          { title: 'イベント', value: 'event' },
          { title: 'FAQ', value: 'faq' }
        ]
      },
      validation: Rule => Rule.required()
    }),

    defineField({
      name: 'extractedContent',
      title: '抽出されたコンテンツ',
      description: '元コンテンツから抽出・最適化されたテキスト',
      type: 'text',
      group: 'basic'
    }),

    // ========== 関連情報 ==========
    defineField({
      name: 'originalContent',
      title: '元のコンテンツ',
      description: 'このAI最適化コンテンツの元となったドキュメント',
      type: 'reference',
      group: 'relations',
      to: [
        { type: 'blogPost' },
        { type: 'page' },
        { type: 'news' },
        { type: 'event' },
        { type: 'faqCard' }
      ]
    }),

    defineField({
      name: 'relatedServices',
      title: '関連サービス',
      type: 'array',
      group: 'relations',
      of: [
        {
          type: 'reference',
          to: [{ type: 'service' }]
        }
      ]
    }),

    defineField({
      name: 'relatedPersons',
      title: '関連人物',
      type: 'array',
      group: 'relations',
      of: [
        {
          type: 'reference',
          to: [{ type: 'person' }]
        }
      ]
    }),

    // ========== メタデータ ==========
    defineField({
      name: 'publishedAt',
      title: '公開日',
      type: 'datetime',
      group: 'basic'
    }),

    defineField({
      name: 'lastOptimized',
      title: '最終最適化日',
      type: 'datetime',
      group: 'ai',
      initialValue: () => new Date().toISOString()
    }),

    defineField({
      name: 'isActive',
      title: '有効',
      type: 'boolean',
      initialValue: true
    }),

    defineField({
      name: 'autoGenerated',
      title: '自動生成',
      description: 'このコンテンツが自動生成されたかどうか',
      type: 'boolean',
      initialValue: true
    })
  ],

  preview: {
    select: {
      title: 'title',
      contentType: 'contentType',
      priority: 'aiPriority',
      keywords: 'aiSearchKeywords'
    },
    prepare(selection) {
      const { title, contentType, priority, keywords } = selection
      return {
        title,
        subtitle: `${contentType} | 優先度: ${priority} | キーワード: ${keywords?.slice(0, 3).join(', ') || '未設定'}`
      }
    }
  }
})